### ISSUE TITLE
south migration complaining about avocado_datafield.indexable

### ISSUE THREAD

**Issue by leipzig** [chop-dbhi/varify-data-warehouse#30]
```
Error in migration: variants:0005_add_variantphenotype_hgmd_id
Traceback (most recent call last):
  File "./bin/manage.py", line 13, in <module>
    execute_from_command_line()
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/south/migration/migrators.py", line 229, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/south/migration/migrators.py", line 304, in migrate_many
    result = self.migrate(migration, database)
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/south/migration/migrators.py", line 129, in migrate
    result = self.run(migration, database)
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/south/migration/migrators.py", line 113, in run
    return self.run_migration(migration, database)
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/south/migration/migrators.py", line 83, in run_migration
    migration_function()
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/south/migration/migrators.py", line 59, in <lambda>
    return (lambda: direction(orm))
  File "./vdw/variants/migrations/0005_add_variantphenotype_hgmd_id.py", line 13, in forwards
    f = DataField.objects.get_by_natural_key('variants.variantphenotype.hgmd_id')
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/avocado/managers.py", line 162, in get_by_natural_key
    return queryset.get(**dict(zip(keys, values)))
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/django/db/models/query.py", line 361, in get
    num = len(clone)
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/django/db/models/query.py", line 85, in __len__
    self._result_cache = list(self.iterator())
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/nas/is1/leipzig/chop-varify-env/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 52, in execute
    return self.cursor.execute(query, args)
django.db.utils.DatabaseError: column avocado_datafield.indexable does not exist
LINE 1: ...."category_id", "avocado_datafield"."enumerable", "avocado_d...
```

**Comment by bruth** [comment]
It appears the migration shown is [not using](https://github.com/cbmi/varify-data-warehouse/blob/master/vdw/variants/migrations/0005_add_variantphenotype_hgmd_id.py#L10-L17) the South mechanisms models (e.g. `orm['avocado.DataField']`) to perform the migration and it is trying to save a `DataField` when before the Avocado migrations have been applied.

To fix your immediate problem, migrate avocado first, then trying migrating vdw again. Thanks for the report.
